apiVersion: v1
kind: Pod
metadata: 
  name: test-pd

spec:
  containers:
    - image: k8s.gcr.io/test-webserver
      name: my-app
      volumeMounts: 
        - mountPath: /test-pd
          name: test-volume

  volumes:
    - name: test-volume
      hostPath:
        path: /usr/local #directory on the the node server
        type: Directory #optional